var data = [
  {
    id: 0,
    Name: "Ahmed Ali",
    f_Name: "Yaqoob Ali",
    class: "VB",
    contact: "0311-823674",
    profile: "student_images/s1.jpg",
    gender: "Male",
    dept: "Bio",
  },
  {
    id: 1,
    Name: "Yasir",
    f_Name: "Mahmood",
    class: "VB",
    contact: "0311-823674",
    profile: "student_images/s2.jpg",
    gender: "Male",
    dept: "Engineering",
  },
  {
    id: 2,
    Name: "Ali Khan",
    f_Name: "Tameez khan",
    class: "VB",
    contact: "0311-823674",
    profile: "student_images/s3.jpg",
    gender: "Male",
    dept: "Bio",
  },
  {
    id: 3,
    Name: "Maria Khan",
    f_Name: "Bilal Khan",
    class: "VB",
    contact: "0311-823674",
    profile: "student_images/s4.jpg",
    gender: "Male",
    dept: "Engineering",
  },
  {
    id: 4,
    Name: "Farooq Hadiyat",
    f_Name: "Hadiayat",
    class: "VB",
    contact: "0311-823674",
    profile: "student_images/s5.jpg",
    gender: "Male",
    dept: "Engineering",
  },
  {
    id: 5,
    Name: "Alia",
    f_Name: "khan Ali",
    class: "VB",
    contact: "0311-823674",
    profile: "student_images/s5.jpg",
    gender: "Female",
    dept: "Bio",
  },
  {
    id: 6,
    Name: "Khan zadi",
    f_Name: "khan Ali",
    class: "ViB",
    contact: "0311-823674",
    profile: "student_images/s2.jpg",
    gender: "Female",
    dept: "Engineering",
  },
];